# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'shotgun'
gem 'sinatra'

group :test, :development do
  gem 'factory_bot'
  gem 'pry'
  gem 'rack-test', require: 'rack/test'
  gem 'rspec'
end
